var module=require("./module/fsModule.js");
console.log(module);
module.read("./module/text1.txt");
module.write("./module/text2.txt");
module.copy("./module/text1.txt","./module/text3.txt");
module.del("./module/text4.txt");
module.create("./module/text");
module.rename("./module/text.txt","./module/text0.txt");
module.append("./module/text1.txt","今天的讲解到此结束，欲知结局如何，请听下回分解");
module.fileState("./module/text1.txt");
module.flag("./module/text4.txt");
module.appendCopy("./module/text3.txt","./module/text4.txt");
module.readStream("./module/text1.txt");
module.writeStream("./module/text2.txt");
module.copyStream("./module/text1.txt","./module/text0.txt");